project_id = "prksphzxxawvaootvwau"

[functions.send-comment-notification]
verify_jwt = false

[functions.generate-ai-comments]
verify_jwt = false

[functions.post-pending-comments]
verify_jwt = false

[functions.trigger-ai-comments]
verify_jwt = false

[functions.generate-ai-posts]
verify_jwt = false

[functions.manage-email-alias]
verify_jwt = false

[functions.notify-advertise-inquiry]
verify_jwt = false
