import { Link } from "react-router-dom";
import { useLocalizedNavigate } from "@/hooks/useLocalizedNavigate";
import { useLanguage } from "@/hooks/useLanguage";
import { ArrowLeft, DollarSign, BarChart3, Target, Megaphone } from "lucide-react";
import { Button } from "@/components/ui/button";
import Footer from "@/components/Footer";

const MonetizationSolutions = () => {
  const { localePath } = useLocalizedNavigate();
  const { language } = useLanguage();
  const isTr = language === "tr";

  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl py-8 px-4">
        <Link to={localePath("/")}>
          <Button variant="ghost" size="sm" className="mb-6 gap-2">
            <ArrowLeft className="h-4 w-4" />
            {isTr ? "Ana Sayfa" : "Home"}
          </Button>
        </Link>

        <h1 className="text-4xl font-bold text-primary mb-4">
          {isTr ? "Yayıncılar İçin Gelir Çözümleri" : "Monetization Solutions for Publishers"}
        </h1>
        <p className="text-muted-foreground mb-8 text-lg">
          {isTr
            ? "İçeriklerinizden gelir elde etmenin en etkili yolları."
            : "The most effective ways to monetize your content."}
        </p>

        <div className="grid md:grid-cols-2 gap-6">
          {[
            { icon: DollarSign, title: isTr ? "Gelir Paylaşımı" : "Revenue Sharing", desc: isTr ? "İçeriklerinizin oluşturduğu reklam gelirinden pay alın. Şeffaf ve adil ödeme sistemi." : "Earn a share of ad revenue generated by your content. Transparent and fair payment system." },
            { icon: BarChart3, title: isTr ? "Analitik Panel" : "Analytics Dashboard", desc: isTr ? "Detaylı performans metrikleri ile içeriklerinizin başarısını takip edin." : "Track your content performance with detailed analytics and metrics." },
            { icon: Target, title: isTr ? "Hedefli Kampanyalar" : "Targeted Campaigns", desc: isTr ? "Sponsorlu içerik kampanyaları ile gelir kaynağınızı çeşitlendirin." : "Diversify your revenue with sponsored content campaigns." },
            { icon: Megaphone, title: isTr ? "Marka İşbirlikleri" : "Brand Partnerships", desc: isTr ? "Büyük markalarla iş birliği fırsatlarına erişin." : "Access partnership opportunities with major brands." },
          ].map((item, i) => (
            <div key={i} className="rounded-xl border border-border bg-card p-6 space-y-3">
              <item.icon className="h-8 w-8 text-primary" />
              <h3 className="text-lg font-semibold">{item.title}</h3>
              <p className="text-muted-foreground text-sm">{item.desc}</p>
            </div>
          ))}
        </div>

        <div className="mt-8 rounded-xl border border-primary/30 bg-primary/5 p-6 text-center">
          <h2 className="text-xl font-bold mb-2">{isTr ? "Hemen Başlayın" : "Get Started Today"}</h2>
          <p className="text-muted-foreground mb-4 text-sm">
            {isTr ? "publishers@ondabir.com adresine e-posta göndererek başvurun." : "Apply by sending an email to publishers@ondabir.com"}
          </p>
          <Button>{isTr ? "İletişime Geç" : "Contact Us"}</Button>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default MonetizationSolutions;
