import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { HelpCircle } from "lucide-react";

const faqs = [
  {
    q: "How does the AI content detector work?",
    a: "Our detector uses large language models and forensic signal analysis to estimate the probability that a piece of content was generated by AI. For text, it analyzes perplexity, burstiness, and token-level patterns. For images and video, it checks for diffusion artifacts, lighting inconsistencies, and deepfake signatures.",
  },
  {
    q: "What do the probability scores mean?",
    a: "The AI probability percentage reflects how confident the model is that the content is AI-generated. A score near 0% strongly suggests human authorship, while a score near 100% strongly suggests AI generation. The verdict badge (Human, Likely Human, Uncertain, Likely AI, AI) groups these percentages into actionable categories.",
  },
  {
    q: "How accurate is the detection?",
    a: "Accuracy varies by content type and model. Text detection is generally strongest for popular models like ChatGPT and Claude, while image detection excels at spotting Midjourney, DALL·E, and Stable Diffusion outputs. Results are probabilistic and should be combined with human judgment, not used as legal proof.",
  },
  {
    q: "Can it detect all AI models?",
    a: "We continuously update our detection signatures to cover major models including ChatGPT, Claude, Gemini, Llama, Mistral, DeepSeek, Midjourney, DALL·E, Stable Diffusion, Flux, Sora, Runway, and more. Newer or highly customized models may be harder to detect until we train on their artifacts.",
  },
  {
    q: "What file formats are supported?",
    a: "Text: paste directly. Images: PNG, JPG, WEBP up to 10MB. Videos: MP4, MOV, WEBM up to 20MB. URLs: YouTube, Vimeo, TikTok, X, Instagram, and Facebook public links are supported for video analysis.",
  },
  {
    q: "Is my uploaded content stored or shared?",
    a: "Uploaded files are analyzed in real-time and are not permanently stored. If you generate a shareable result link, a preview thumbnail may be stored temporarily. Text snippets are saved with your shareable results so you can revisit them later on this device.",
  },
  {
    q: "Why did my human-written text score as AI?",
    a: "Highly polished, grammatically perfect writing — especially in formal, academic, or technical styles — can sometimes trigger AI detection. The detector may flag consistent sentence structure or low perplexity that also occurs in human writing. Use the signals list to understand which patterns influenced the score.",
  },
  {
    q: "How can I improve detection accuracy?",
    a: "For best results, provide content in its original form without heavy editing. Longer text samples (200+ words) produce more reliable scores. For images, avoid screenshots or compressed copies; upload the original file. For video, ensure the link is public and the thumbnail is representative.",
  },
];

const DetectorFAQ = () => (
  <Card className="mt-12">
    <CardHeader>
      <CardTitle className="flex items-center gap-2">
        <HelpCircle className="size-5 text-primary" />
        Frequently Asked Questions
      </CardTitle>
    </CardHeader>
    <CardContent>
      <Accordion type="single" collapsible className="w-full">
        {faqs.map((faq, i) => (
          <AccordionItem key={i} value={`item-${i}`}>
            <AccordionTrigger className="text-left text-sm sm:text-base">
              {faq.q}
            </AccordionTrigger>
            <AccordionContent className="text-muted-foreground leading-relaxed">
              {faq.a}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </CardContent>
  </Card>
);

export default DetectorFAQ;
